# Generated by Django 3.0.4 on 2020-04-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportingdata',
            name='model_brand',
            field=models.CharField(choices=[], max_length=2),
        ),
        migrations.AlterField(
            model_name='reportingdata',
            name='model_brand',
            field=models.CharField(choices=[], max_length=2),
        ),
    ]
