# Generated by Django 3.0.4 on 2020-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20200415_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportingdata',
            name='model_brand',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportingdata',
            name='model_brand',
            field=models.TextField(max_length=100),
        ),
    ]
