# Generated by Django 3.0.4 on 2020-04-16 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('EX', 'Extron'), ('LE', 'Lectern'), ('AM', 'Amplifier'), ('SP', 'Speaker'), ('MO', 'PC Monitor'), ('CA', 'Cable'), ('NA', 'None')], default='NA', max_length=2)),
                ('equipment', models.CharField(choices=[('OT', 'Other'), ('CO', 'Controller'), ('TO', 'Touchscreen'), ('SW', 'Switcher'), ('DE', 'Audio De-embedder'), ('TX', 'HDMI Transmitter'), ('RX', 'HDMI Receiver'), ('DA', 'HDMI DA'), ('AM', 'Amplifier'), ('TP', 'Twisted Pair'), ('PS', 'Power Supply'), ('PI', 'Power Injector'), ('IN', 'Infrastructure'), ('BD', 'Blu-Ray Drive'), ('BC', 'Blu-Ray Case'), ('VP', 'VoIP Box'), ('PH', 'Phone Handset'), ('PR', 'Phone Ringer'), ('KS', 'Key Switch'), ('PW', 'Power Strip'), ('DC', 'Doc Cam'), ('DM', 'Doc Cam Mount'), ('IE', 'IEC'), ('BF', 'Blu-Ray Fan'), ('SS', 'Small Speaker'), ('SM', 'Medium Speaker'), ('SL', 'Large Speaker'), ('SC', 'Ceiling Speaker'), ('MO', 'Monitor'), ('HD', 'HDMI'), ('VG', 'VGA'), ('AU', 'Audio'), ('US', 'USB')], default='OT', max_length=2)),
                ('model_brand', models.CharField(max_length=100, unique=True)),
                ('quantity_deployed', models.PositiveIntegerField(default=0)),
                ('keep_in_stock', models.PositiveIntegerField(default=0)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('relevant_link', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(default='N/A', max_length=254)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInventoryData',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('category', models.CharField(choices=[('EX', 'Extron'), ('LE', 'Lectern'), ('AM', 'Amplifier'), ('SP', 'Speaker'), ('MO', 'PC Monitor'), ('CA', 'Cable'), ('NA', 'None')], default='NA', max_length=2)),
                ('equipment', models.CharField(choices=[('OT', 'Other'), ('CO', 'Controller'), ('TO', 'Touchscreen'), ('SW', 'Switcher'), ('DE', 'Audio De-embedder'), ('TX', 'HDMI Transmitter'), ('RX', 'HDMI Receiver'), ('DA', 'HDMI DA'), ('AM', 'Amplifier'), ('TP', 'Twisted Pair'), ('PS', 'Power Supply'), ('PI', 'Power Injector'), ('IN', 'Infrastructure'), ('BD', 'Blu-Ray Drive'), ('BC', 'Blu-Ray Case'), ('VP', 'VoIP Box'), ('PH', 'Phone Handset'), ('PR', 'Phone Ringer'), ('KS', 'Key Switch'), ('PW', 'Power Strip'), ('DC', 'Doc Cam'), ('DM', 'Doc Cam Mount'), ('IE', 'IEC'), ('BF', 'Blu-Ray Fan'), ('SS', 'Small Speaker'), ('SM', 'Medium Speaker'), ('SL', 'Large Speaker'), ('SC', 'Ceiling Speaker'), ('MO', 'Monitor'), ('HD', 'HDMI'), ('VG', 'VGA'), ('AU', 'Audio'), ('US', 'USB')], default='OT', max_length=2)),
                ('model_brand', models.CharField(db_index=True, max_length=100)),
                ('quantity_deployed', models.PositiveIntegerField(default=0)),
                ('keep_in_stock', models.PositiveIntegerField(default=0)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('relevant_link', models.TextField(max_length=400)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inventory data',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
